version: '3.8'

services:
  # Development application service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fera-ai-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5173:5173"  # Vite dev server
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
    networks:
      - fera-dev-network
    command: npm run dev
    stdin_open: true
    tty: true

  # Redis for development
  redis-dev:
    image: redis:alpine
    container_name: fera-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fera-dev-network
    command: redis-server --loglevel debug

  # Redis Commander for Redis GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: fera-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis-dev:6379
    ports:
      - "8081:8081"
    networks:
      - fera-dev-network
    depends_on:
      - redis-dev

networks:
  fera-dev-network:
    driver: bridge